version: 2
sphinx:
  configuration: docs/source/conf.py
formats: all
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - path: .