"""
    A swagger API

    powered by Flasgger  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eto.internal
from eto.internal.model.coco_source import CocoSource
globals()['CocoSource'] = CocoSource
from eto.internal.model.coco_config import CocoConfig


class TestCocoConfig(unittest.TestCase):
    """CocoConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCocoConfig(self):
        """Test CocoConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CocoConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
