"""
    A swagger API

    powered by Flasgger  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eto.internal
from eto.internal.model.create_job_request import CreateJobRequest


class TestCreateJobRequest(unittest.TestCase):
    """CreateJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateJobRequest(self):
        """Test CreateJobRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateJobRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
